set(CMAKE_SYSTEM_NAME Windows)

if(DEFINED ENV{TOOLCHAIN_BIN})
    set(TOOLCHAIN_BIN "$ENV{TOOLCHAIN_BIN}")
endif()

if(NOT DEFINED TOOLCHAIN_BIN)
    message(FATAL_ERROR "TOOLCHAIN_BIN not set")
endif()

set(CMAKE_C_COMPILER "${TOOLCHAIN_BIN}/gcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BIN}/g++.exe")
set(CMAKE_AR "${TOOLCHAIN_BIN}/ar.exe")
set(CMAKE_RANLIB "${TOOLCHAIN_BIN}/ranlib.exe")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
